registerCodeEditorInfos('checkargs', [[
bool valid = checkarg.any(any value, table opts)
bool valid = checkarg.float(any value, table opts)
bool valid = checkarg.int(any value, table opts)
bool valid = checkarg.string(any value, table opts)
bool valid = checkarg.bool(any value, table opts)
bool valid = checkarg.table(any value, table opts)
bool valid = checkarg.func(any value, table opts)
bool valid = checkarg.handle(any value, table opts)
bool valid = checkarg.object(any value, table opts)
bool valid = checkarg.union(any value, table opts)
... = checkargsEx(table opts, table types, ...)
... = checkargs(table types, ...)
]])
