registerCodeEditorInfos('checkargs', [[
bool valid = checkargs.checkarg.any(any value, map opts)
bool valid = checkargs.checkarg.float(any value, map opts)
bool valid = checkargs.checkarg.int(any value, map opts)
bool valid = checkargs.checkarg.string(any value, map opts)
bool valid = checkargs.checkarg.bool(any value, map opts)
bool valid = checkargs.checkarg.table(any value, map opts)
bool valid = checkargs.checkarg.func(any value, map opts)
bool valid = checkargs.checkarg.handle(any value, map opts)
bool valid = checkargs.checkarg.object(any value, map opts)
bool valid = checkargs.checkarg.union(any value, map opts)
... = checkargs.checkargsEx(map opts, table types, ...)
... = checkargs(table types, ...)
]])
