registerCodeEditorInfos('checkargs', [[
any value = checkargs.checkarg.any(any value, map opts)
any value = checkargs.checkarg.float(any value, map opts)
any value = checkargs.checkarg.int(any value, map opts)
any value = checkargs.checkarg.string(any value, map opts)
any value = checkargs.checkarg.bool(any value, map opts)
any value = checkargs.checkarg.table(any value, map opts)
any value = checkargs.checkarg.func(any value, map opts)
any value = checkargs.checkarg.object(any value, map opts)
any value = checkargs.checkarg.union(any value, map opts)
any value = checkargs.checkarg.handle(any value, map opts)
any value = checkargs.checkarg.matrix(any value, map opts)
any value = checkargs.checkarg.vector(any value, map opts)
any value = checkargs.checkarg.vector3(any value, map opts)
any value = checkargs.checkarg.quaternion(any value, map opts)
any value = checkargs.checkarg.pose(any value, map opts)
any value = checkargs.checkarg.color(any value, map opts)
... = checkargs.checkargsEx(map opts, table types, ...)
... = checkargs(table types, ...)
]])
