registerCodeEditorInfos('mathx', [[
number y = math.abs(number x)
number y = math.acos(number x)
number y = math.asin(number x)
number y = math.atan(number y)
number y = math.atan(number y, number x)
number y = math.atan2(number y, number x)
number y = math.ceil(number x)
number y = math.cos(number x)
number y = math.cosh(number x)
number y = math.deg(number x)
number y = math.exp(number x)
number y = math.floor(number x)
number y = math.fmod(number x, number f)
number y, number z = math.frexp(number x, number e)
number h = math.hypot(number x, number y)
number y = math.ldexp(number x, number e)
number y = math.log(number x)
number y = math.log10(number x)
number y = math.max(number x1, ...)
number y = math.min(number x1, ...)
number y = math.mod(number x, number f)
number y = math.modf(number x, number f)
number y = math.pow(number x, number exp)
number y = math.rad(number x)
float y = math.random()
int y = math.random(int min, int max)
int y = math.random(int max)
float y = math.random2()
int y = math.random2(int min, int max)
int y = math.random2(int max)
math.randomseed(int x)
math.randomseed2(int x)
int plus_or_minus_one = math.sign(number x)
number y = math.sin(number x)
number y = math.sinh(number x)
number y = math.sqrt(number x)
number y = math.tan(number x)
number y = math.tanh(number x)
int y = math.tointeger(number x)
string type = math.type(number x)
bool b = math.ult(int m, int n)
math.huge
math.pi
]])
