local deprecated = {}

deprecated.functions = {
    {"sim.addBanner", ""},
    {"sim.addGhost", ""},
    {"sim.addObjectToCollection", "sim.addItemToCollection"},
    {"sim.addObjectToSelection", "sim.setObjectSel"},
    {"sim.addStatusbarMessage", "sim.addLog"},
    {"sim.boolAnd32", "Lua's bitwise operators"},
    {"sim.boolOr32", "Lua's bitwise operators"},
    {"sim.boolXor32", "Lua's bitwise operators"},
    {"sim.breakForceSensor", "sim.setObjectParent"},
    {"sim.buildMatrixQ", "sim.poseToMatrix"},
    {"sim.checkIkGroup", "the simIK functionality"},
    {"sim.clearDoubleSignal", "sim.removeProperty(sim.handle_scene, 'signal.signalName')"},
    {"sim.clearIntegerSignal", "sim.removeProperty(sim.handle_scene, 'signal.signalName')"},
    {"sim.closeModule", ""},
    {"sim.closeTextEditor", "sim.textEditorClose"},
    {"sim.computeJacobian", "the simIK functionality"},
    {"sim.copyMatrix", "table.copy"},
    {"sim.createIkElement", "the simIK functionality"},
    {"sim.createIkGroup", "the simIK functionality"},
    {"sim.createMeshShape", "sim.createShape"},
    {"sim.createPureShape", "sim.createPrimitiveShape"},
    {"sim.displayDialog", "the simUI functionality"},
    {"sim.emptyCollection", "sim.destroyCollection"},
    {"sim.endDialog", "the simUI functionality"},
    {"sim.exportIk", "the simIK functionality"},
    {"sim.fileDialog", "the simUI functionality"},
    {"sim.generateIkPath", "the simIK functionality"},
    {"sim.getArrayParameter", "properties"},
    {"sim.getBoolParameter", "properties"},
    {"sim.getCollectionHandle", "sim.createCollection"},
    {"sim.getCollectionName", ""},
    {"sim.getCollisionHandle", "sim.checkCollision"},
    {"sim.getConfigForTipPose", "the simIK functionality"},
    {"sim.getConfigurationTree", ""},
    {"sim.getCustomizationScriptAssociatedWithObject", "sim.getObject"},
    {"sim.getDialogInput", "the simUI functionality"},
    {"sim.getDialogResult", "the simUI functionality"},
    {"sim.getDistanceHandle", "sim.checkDistance"},
    {"sim.getDoubleSignal", "sim.getFloatProperty(sim.handle_scene, 'signal.signalName')"},
    {"sim.getEngineBoolParameter", "properties"},
    {"sim.getEngineFloatParameter", "properties"},
    {"sim.getEngineInt32Parameter", "properties"},
    {"sim.getFloatParameter", "properties"},
    {"sim.getIkGroupHandle", "the simIK functionality"},
    {"sim.getIkGroupMatrix", "the simIK functionality"},
    {"sim.getInt32Parameter", "properties"},
    {"sim.getIntegerSignal", "sim.getIntProperty(sim.handle_scene, 'signal.signalName')"},
    {"sim.getJointMatrix", "sim.getObjectChildPose"},
    {"sim.getJointMaxForce", "sim.getJointTargetForce"},
    {"sim.getModuleInfo", "sim.getPluginInfo"},
    {"sim.getModuleName", "sim.getPluginName"},
    {"sim.getObjectAssociatedWithScript", "sim.getObject"},
    {"sim.getObjectConfiguration", ""},
    {"sim.getObjectFloatParameter", "properties"},
    {"sim.getObjectHandle", "sim.getObject"},
    {"sim.getObjectName", "sim.getObjectAlias"},
    {"sim.getObjectSelection", "sim.getObjectSel"},
    {"sim.getObjectSizeValues", ""},
    {"sim.getObjectStringParameter", "properties"},
    {"sim.getObjectUniqueIdentifier", "sim.getObjectUid"},
    {"sim.getQuaternionFromMatrix", "sim.matrixToPose"},
    {"sim.getScriptAssociatedWithObject", "sim.getObject"},
    {"sim.getScriptAttribute", "properties"},
    {"sim.getScriptHandle", "sim.getObject"},
    {"sim.getScriptName", "sim.getScriptStringParam"},
    {"sim.getShapeMassAndInertia", "sim.getShapeMass and/or sim.getShapeInertia"},
    {"sim.getStringNamedParam", "sim.getStringProperty(sim.handle_app, 'namedParam.nam')"},
    {"sim.getStringParameter", "properties"},
    {"sim.getSystemTimeInMs", "sim.getSystemTime"},
    {"sim.getThreadAutomaticSwitch", ""},
    {"sim.getThreadExitRequest", "sim.getSimulationStopping"},
    {"sim.getThreadSwitchAllowed", ""},
    {"sim.getThreadSwitchTiming", ""},
    {"sim.getVisionSensorCharImage", "sim.getVisionSensorImg"},
    {"sim.getVisionSensorDepthBuffer", "sim.getVisionSensorDepth"},
    {"sim.getVisionSensorImage", "sim.getVisionSensorImg"},
    {"sim.getVisionSensorResolution", "sim.getVisionSensorImg"},
    {"sim.handleCollision", "sim.checkCollision"},
    {"sim.handleCustomizationScripts", "sim.handleEmbeddedScripts"},
    {"sim.handleDistance", "sim.checkDistance"},
    {"sim.handleIkGroup", "the simIK functionality"},
    {"sim.handleModule", ""},
    {"sim.isDeprecated", ""},
    {"sim.isObjectInSelection", "sim.getObjectSel"},
    {"sim.loadModule", "sim.loadPlugin"},
    {"sim.modifyGhost", ""},
    {"sim.msgBox", "the simUI functionality"},
    {"sim.openModule", ""},
    {"sim.readCollision", "sim.checkCollision"},
    {"sim.readCustomDataBlock", "properties"},
    {"sim.readCustomDataBlockTags", "properties"},
    {"sim.readDistance", "sim.checkDistance"},
    {"sim.receiveData", ""},
    {"sim.registerScriptFunction", ""},
    {"sim.removeBanner", ""},
    {"sim.removeCollection", "sim.destroyCollection"},
    {"sim.removeIkGroup", "the simIK functionality"},
    {"sim.removeObject", "sim.removeObjects"},
    {"sim.removeObjectFromSelection", "sim.setObjectSel"},
    {"sim.reorientShapeBoundingBox", "sim.alignShapeBB and/or sim.relocateShapeFrame"},
    {"sim.resetCollision", "sim.checkCollision"},
    {"sim.resetDistance", "sim.checkDistance"},
    {"sim.rmlMoveToJointPositions", "sim.moveToConfig"},
    {"sim.rmlMoveToPosition", "sim.moveToPose"},
    {"sim.rmlPos", "sim.ruckigPos"},
    {"sim.rmlRemove", "sim.ruckigRemove"},
    {"sim.rmlStep", "sim.ruckigStep"},
    {"sim.rmlVel", "sim.ruckigVel"},
    {"sim.sendData", ""},
    {"sim.setArrayParameter", "properties"},
    {"sim.setBoolParameter", "properties"},
    {"sim.setCollectionName", ""},
    {"sim.setConfigurationTree", ""},
    {"sim.setDebugWatchList", ""},
    {"sim.setDoubleSignal", "sim.setFloatProperty(sim.handle_scene, 'signal.signalName')"},
    {"sim.setEngineBoolParameter", "properties"},
    {"sim.setEngineFloatParameter", "properties"},
    {"sim.setEngineInt32Parameter", "properties"},
    {"sim.setFloatParameter", "properties"},
    {"sim.setGraphUserData", "sim.setGraphStreamValue"},
    {"sim.setIkElementProperties", "the simIK functionality"},
    {"sim.setIkGroupProperties", "the simIK functionality"},
    {"sim.setInt32Parameter", "properties"},
    {"sim.setIntegerSignal", "sim.setIntProperty(sim.handle_scene, 'signal.signalName')"},
    {"sim.setJointForce", "sim.setJointTargetForce"},
    {"sim.setJointMaxForce", "sim.setJointTargetForce"},
    {"sim.setObjectConfiguration", ""},
    {"sim.setObjectFloatParameter", "properties"},
    {"sim.setObjectInt32Parameter", "properties"},
    {"sim.setObjectName", "sim.setObjectAlias"},
    {"sim.setObjectSelection", "sim.setObjectSel"},
    {"sim.setObjectSizeValues", ""},
    {"sim.setObjectStringParameter", "properties"},
    {"sim.setScriptAttribute", "properties"},
    {"sim.setScriptText", "sim.createScript"},
    {"sim.setScriptVariable", ""},
    {"sim.setShapeMassAndInertia", "sim.getShapeMass and/or sim.setShapeIntertia"},
    {"sim.setShapeMaterial", ""},
    {"sim.setSphericalJointMatrix", "sim.setObjectChildPose"},
    {"sim.setStringNamedParam", "sim.setStringProperty(sim.handle_app, 'namedParam.name', value)"},
    {"sim.setStringParameter", "properties"},
    {"sim.setThreadAutomaticSwitch", "sim.setStepping"},
    {"sim.setThreadSwitchAllowed", "sim.acquireLock and sim.releaseLock"},
    {"sim.setThreadSwitchTiming", "sim.setAutoYieldDelay"},
    {"sim.setVisionSensorCharImage", "sim.setVisionSensorImg"},
    {"sim.setVisionSensorImage", "sim.setVisionSensorImg"},
    {"sim.switchThread", "sim.step"},
    {"sim.unloadModule", "sim.unloadPlugin"},
    {"sim.writeCustomDataBlock", "properties"},
    {"sim.convexDecompose", "the simConvex functionality"},
    {"sim.getQHull", "simConvex.qhull"},
    {"sim.getDecimatedMesh", "simOpenMesh.decimate"},
    {"sim.addScript", "sim.createScript"},
    {"sim.associateScriptWithObject", "sim.createScript / sim.setObjectParent"},
    {"sim.removeScript", "sim.removeObject"},
    {"sim.getScriptInt32Param", "properties"},
    {"sim.setScriptInt32Param", "properties"},
    {"sim.getScriptStringParam", "properties"},
    {"sim.setScriptStringParam", "properties"},
    {"sim.persistentDataWrite", "properties"},
    {"sim.persistentDataRead", "properties"},
    {"sim.getPersistentDataTags", "properties"},
    {"sim.getMatchingPersistentDataTags", "properties"},

    --]]
}

function deprecated.extend(sim)
    local n = sim.getInt32Param(sim.intparam_notifydeprecated)
    if sim.getScriptInt32Param(sim.handle_self, sim.scriptintparam_type) == sim.scripttype_main then return end
    if n <= 0 then return end
    local inf = ''
    if n == 1 then
        inf = ' (control verbosity via notifyDeprecated in usrset.txt)'
    end
    for _, pair in ipairs(deprecated.functions) do
        local old, new = table.unpack(pair)
        assert(old:sub(1, 4) == 'sim.')
        local msg
        if new == '' then
            msg = string.format('%s is deprecated and the related functionality will disappear in a future release.', old) .. inf
        else
            msg = string.format('%s is deprecated. please use %s instead.', old, new) .. inf
        end
        old = old:sub(5)
        sim[old] = wrap(sim[old], function(origFunc)
            return function(...)
                sim.addLog(sim.verbosity_scriptwarnings | sim.verbosity_once, msg .. (n > 1 and debug.traceback('', 2) or ''))
                return origFunc(...)
            end
        end)
    end
end

return deprecated
