-- simAssimp lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

local simAssimp=require('simAssimp')

__initFunctions=__initFunctions or {}
table.insert(__initFunctions, function()
    local function wrapFunc(funcName,wrapperGenerator)
        _G['simAssimp'][funcName]=wrapperGenerator(_G['simAssimp'][funcName])
    end

    wrapFunc('importDlg',function(origFunc)
        return function(...)
            filename=checkargsEx(
                {level=1},
                {
                    {type='string'},
                },
                ...
            )
            return origFunc(filename)
        end
    end)

    wrapFunc('exportDlg',function(origFunc)
        return function(...)
            filename=checkargsEx(
                {level=1},
                {
                    {type='string'},
                },
                ...
            )
            return origFunc(filename)
        end
    end)

end)

return simAssimp
