-- simB0 lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

local simB0=require('simB0')

__initFunctions=__initFunctions or {}
table.insert(__initFunctions, function()
    local function wrapFunc(funcName,wrapperGenerator)
        _G['simB0'][funcName]=wrapperGenerator(_G['simB0'][funcName])
    end

    wrapFunc('nodeSpin',function(origFunc)
        return function(...)
            handle=checkargsEx(
                {level=1},
                {
                    {type='string'},
                },
                ...
            )
            return origFunc(handle)
        end
    end)

    wrapFunc('pingResolver',function(origFunc)
        return function(...)
            checkargsEx(
                {level=1},
                {
                },
                ...
            )
            return origFunc()
        end
    end)

    wrapFunc('serviceClientCallJSON',function(origFunc)
        return function(...)
            serviceClientHandle=checkargsEx(
                {level=1},
                {
                    {type='string'},
                },
                ...
            )
            return origFunc(serviceClientHandle)
        end
    end)

end)

return simB0
