-- simGLTF lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

local simGLTF=require('simGLTF')

__initFunctions=__initFunctions or {}
table.insert(__initFunctions, function()
    local function wrapFunc(funcName,wrapperGenerator)
        _G['simGLTF'][funcName]=wrapperGenerator(_G['simGLTF'][funcName])
    end

end)

return simGLTF
