-- simICP lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

local simICP=require('simICP')

__initFunctions=__initFunctions or {}
table.insert(__initFunctions, function()
    local function wrapFunc(funcName,wrapperGenerator)
        _G['simICP'][funcName]=wrapperGenerator(_G['simICP'][funcName])
    end

end)

return simICP
