-- simLuaCmd lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

local simLuaCmd=require('simLuaCmd')

__initFunctions=__initFunctions or {}
table.insert(__initFunctions, function()
    local function wrapFunc(funcName,wrapperGenerator)
        _G['simLuaCmd'][funcName]=wrapperGenerator(_G['simLuaCmd'][funcName])
    end

end)

return simLuaCmd
