-- simSDF lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

local simSDF=require('simSDF')

__initFunctions=__initFunctions or {}
table.insert(__initFunctions, function()
    local function wrapFunc(funcName,wrapperGenerator)
        _G['simSDF'][funcName]=wrapperGenerator(_G['simSDF'][funcName])
    end

end)

return simSDF
