-- simZMQ lua type-checking wrapper
-- (this file is automatically generated: do not edit)
require 'checkargs'

local simZMQ=require('simZMQ')

__initFunctions=__initFunctions or {}
table.insert(__initFunctions, function()
    local function wrapFunc(funcName,wrapperGenerator)
        _G['simZMQ'][funcName]=wrapperGenerator(_G['simZMQ'][funcName])
    end

end)

return simZMQ
